#---------------------------
# Script Description
#---------------------------
'Sch_extract_integrin_genes.py is a Python script designed to identify and extract'
'candidate integrin proteins from schistosome proteome datasets using Pfam domain'
'annotations generated by HMMER. The script parses the HMMER domtblout output file'
'to detect proteins containing integrin-associated Pfam domains, including Integrin_alpha,'
'Integrin_beta, FG-GAP repeats, PSI domains, and integrin EGF-like domains'
'Proteins with significant domain hits (independent domain E-value ≤ 1e-5) are classified'
'into their respective integrin domain families. The script then retrieves the corresponding'
'sequences from the input FASTA file and outputs:'
'1. Family-specific FASTA files containing candidate integrin proteins.'
'2. An Excel summary table listing detected proteins, associated Pfam domains, E-values, and sequence lengths'
'This script facilitates rapid identification and organization of integrin-related genes in'
'schistosome genomes or proteomes, enabling downstream analyses such as sequence'
'alignment, phylogenetic reconstruction, and structural characterization'


import os
import sys
import argparse
import pandas as pd
from Bio import SeqIO
import re
from collections import defaultdict

from collections import OrderedDict

def _norm_seq(seq):
    """Normalize for deduplication: uppercase, remove gaps/whitespace."""
    return re.sub(r"\s+", "", str(seq)).replace("-", "").upper()

def _dedup_ids_by_sequence(seqs_dict, ids):
    """
    Deduplicate by identical sequence.
    Returns: (kept_ids, dup_map) where dup_map is list of (dup_id, kept_id)
    """
    seen = {}
    kept = []
    dup_map = []
    for pid in ids:
        if pid not in seqs_dict:
            continue
        nseq = _norm_seq(seqs_dict[pid].seq)
        if nseq in seen:
            dup_map.append((pid, seen[nseq]))
        else:
            seen[nseq] = pid
            kept.append(pid)
    return kept, dup_map


# ---- CONFIG ----
DOMAINS = {
    "Integrin_A_Ig_3": ["PF20806.4"],
    "Integrin_alpha2": ["PF20805.4"],
    "FG-GAP": ["PF01839.30"],
    "FG-GAP_3": ["PF13517.13"],
    "Integrin_beta": ["PF00362.25"],
    "EGF_integrin": ["PF23105.2"],
    "Integrin_b_cyt": ["PF08725.17"],
    "PSI_integrin": ["PF17205.10"]
}

DOMTBL = "input/domtblout.txt"
FASTA = "input/proteome.fa"
OUT_XLSX = "results/integrin_candidates.xlsx"
OUT_FASTA_DIR = "results/Pfam_FASTAs"

# ---- OPTIONAL OUTPUTS (ADDED) ----
WRITE_COMBINED_FASTA = True
COMBINED_FASTA = "intermediate/integrin.fasta"
COMBINED_DUP_MAP = "results/integrin_duplicates.tsv"

WRITE_ALPHA_BETA_FASTA = True
OUT_ALPHA_FASTA = "results/Pfam_FASTAs/integrin_alpha.fasta"
OUT_BETA_FASTA  = "results/Pfam_FASTAs/integrin_beta.fasta"


# ---- PARSE HMMER domtblout (FINAL, CORRECT) ----
from collections import defaultdict

hits = defaultdict(list)

# α Pfams: filter using FULL-seq Evalue (alpha repeats can have weak domain iEvalues)
ALPHA_PFAMS_BASE = {"PF20806", "PF20805", "PF01839", "PF13517"}  # base IDs (no version)
CUTOFF = 1e-5

with open(DOMTBL) as f:
    for line in f:
        if line.startswith("#") or not line.strip():
            continue

        parts = line.split()
        if len(parts) < 13:
            continue

        # Your domtblout layout (as in your example):
        # pfam accession is in parts[1], protein id in parts[3]
        pf = parts[1]          # e.g., PF20806.4
        prot = parts[3]        # e.g., Smp_245490.1
        pf_base = pf.split(".")[0]

        # Full-seq Evalue (used for α Pfams)
        try:
            full_ev = float(parts[6])
        except ValueError:
            continue

        # Domain iEvalue (used for non-α Pfams)
        try:
            ie_ev = float(parts[12])
        except ValueError:
            # optional fallback to cEvalue
            try:
                ie_ev = float(parts[11])
            except ValueError:
                continue

        # α: use full-seq; others: use domain iEvalue
        ev_for_filter = full_ev if pf_base in ALPHA_PFAMS_BASE else ie_ev

        if ev_for_filter <= CUTOFF:
            hits[prot].append((pf, ev_for_filter))
        

# ---- LOAD SEQUENCES ----
seqs = {r.id: r for r in SeqIO.parse(FASTA, "fasta")}

records = []

for prot, pfams in hits.items():
    for fam, pfam_list in DOMAINS.items():
        for pf, ev in pfams:
            if pf in pfam_list:
                records.append({
                    "Protein_ID": prot,
                    "Family": fam,
                    "Pfam": pf,
                    "Evalue": ev,
                    "Length": len(seqs[prot])
                })

df = pd.DataFrame(records).drop_duplicates()
if df.empty:
    raise RuntimeError(
        "No integrin Pfam hits detected. "
        "Check Pfam IDs, HMM file, or E-value cutoff."
    )

# beta vs alpha integrin split + combined dedup FASTA ----

# Ensure output folders exist
os.makedirs(os.path.dirname(OUT_XLSX), exist_ok=True)
os.makedirs(os.path.dirname(COMBINED_FASTA) if 'COMBINED_FASTA' in globals() else "results", exist_ok=True)  # safety

# Candidate proteins (those that mapped to DOMAINS)
candidate_ids = sorted(set(df["Protein_ID"].tolist()))

# Classify beta vs alpha by Pfam presence rule:
# beta if BOTH PF00362.25 and PF08725.17 are present for that protein; else alpha
beta_req1 = set(DOMAINS["Integrin_beta"])
beta_req2 = set(DOMAINS["Integrin_b_cyt"])

beta_ids = []
alpha_ids = []

for prot in candidate_ids:
    pfset = set(pf for pf, ev in hits.get(prot, []))
    is_beta = beta_req1.issubset(pfset) and beta_req2.issubset(pfset)
    if is_beta:
        beta_ids.append(prot)
    else:
        alpha_ids.append(prot)

# Write beta/alpha FASTA outputs (optional)
if WRITE_ALPHA_BETA_FASTA:
    os.makedirs(os.path.dirname(OUT_ALPHA_FASTA), exist_ok=True)

    with open(OUT_BETA_FASTA, "w") as f:
        for pid in beta_ids:
            if pid in seqs:
                SeqIO.write(seqs[pid], f, "fasta")

    with open(OUT_ALPHA_FASTA, "w") as f:
        for pid in alpha_ids:
            if pid in seqs:
                SeqIO.write(seqs[pid], f, "fasta")

# Write combined integrin.fasta with duplicates removed (optional)
if WRITE_COMBINED_FASTA:
    os.makedirs(os.path.dirname(COMBINED_FASTA) if 'COMBINED_FASTA' in globals() else "results", exist_ok=True)

    kept_ids, dup_map = _dedup_ids_by_sequence(seqs, candidate_ids)

    with open(COMBINED_FASTA, "w") as f:
        for pid in kept_ids:
            SeqIO.write(seqs[pid], f, "fasta")

    with open(COMBINED_DUP_MAP, "w") as f:
        f.write("duplicate_id\tkept_id\n")
        for dup_id, kept_id in dup_map:
            f.write(f"{dup_id}\t{kept_id}\n")

    print(f"[OK] Combined FASTA written: {COMBINED_FASTA} (kept={len(kept_ids)}, removed_dups={len(dup_map)})")
    if dup_map:
        print(f"[OK] Duplicate map: {COMBINED_DUP_MAP}")


# ---- WRITE FASTA FILES ----
import os
os.makedirs(OUT_FASTA_DIR, exist_ok=True)

for fam in df["Family"].unique():
    with open(f"{OUT_FASTA_DIR}/{fam}.fasta", "w") as f:
        for pid in df[df["Family"] == fam]["Protein_ID"]:
            SeqIO.write(seqs[pid], f, "fasta")

# ---- WRITE EXCEL ----
with pd.ExcelWriter(OUT_XLSX, engine="openpyxl") as writer:
    for fam in df["Family"].unique():
        df[df["Family"] == fam].to_excel(writer, sheet_name=fam, index=False)
    df.to_excel(writer, sheet_name="ALL_CANDIDATES", index=False)

print("Integrin gene extraction complete.")
